### ISSUE TITLE
PlaformException when calling startVerification on Android

### ISSUE THREAD

**Issue by juleshyacinthe** [jeremiahseun/Stripe-Identity#4]
Hi, I've followed the setup instructions from Stripe but I cant start any verification process on Android.

This is my code (working without any issue on iOS):
```dart
try {
  Map<String, dynamic>? result = await stripeService.getStripeIdentityToken();

  final (status, message) = await stripeIdentity.startVerification(
    id: result!['verification_session'],
    key: result['ephemeral_key'],
  );

  if (!context.mounted) return;

  switch (status) {
    case VerificationResult.completed:
      Logger.logInfo('Verification completed successfully');
    case VerificationResult.canceled:
      Logger.logInfo('User canceled verification');
    case VerificationResult.failed:
      Logger.logInfo('Verification failed: $message');
    case VerificationResult.unknown:
      Logger.logInfo('Unknown error occurred: $message');
  }
} catch (err) {
  Logger.logError('Error during get identity token', error: err, stackTrace: StackTrace.current);
}
```

A PlatformException is triggered when trying to start verification on Android:
```
[StripeIdentityPlugin] Attempting to start verification
[StripeIdentityPlugin] Error while starting verification
    The error message is: PlatformException(error, LifecycleOwner com.example.app.MainActivity@37ecea0 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED., null, java.lang.IllegalStateException: LifecycleOwner com.example.app.MainActivity@37ecea0 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
    	at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.kt:93)
    	at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.kt:828)
    	at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.kt:837)
    	at com.stripe.android.identity.StripeIdentityVerificationSheet.<init>(StripeIdentityVerificationSheet.kt:25)
    	at com.stripe.android.identity.IdentityVerificationSheet$Companion.create(IdentityVerificationSheet.kt:84)
    	at com.stripe.identity.identity.StripeIdentityPlugin.startVerification(StripeIdentityPlugin.kt:109)
    	at com.stripe.identity.identity.StripeIdentityPlugin.onMethodCall(StripeIdentityPlugin.kt:71)
    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    	at android.os.Handler.handleCallback(Handler.java:942)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at android.app.ActivityThread.main(ActivityThread.java:7918)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    )
```

If it is of any help, my app is using a `FlutterFragmentActivity` because I'm also using the [flutter_stripe](https://github.com/flutter-stripe/flutter_stripe) package and it is a requirement.
*EDIT* After getting the example project to run on Android 35, I get an error message telling me to use a `FragmentActivity` in the example app, so I guess that this is not the issue.

Flutter doctor output:

```
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.3.1 24D70 darwin-arm64, locale en-US)
    • Flutter version 3.27.3 on channel stable at /Users/jules/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (6 weeks ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/jules/tools/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.97.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by iambenkay** [comment]
Error is familiar to me. Whenever you run certain registration related actions during the `RESUMED` phase of the activity, this error will be thrown.

```kt
// Create an instance of the IdentityVerificationSheet.
        identityVerificationSheet =
            IdentityVerificationSheet.create(activity, configuration) { verificationFlowResult ->
                // Handle the verification result.
                handleVerificationResult(verificationFlowResult, result)
            }

        // Present the verification sheet on the UI thread.
        activity.runOnUiThread {
            identityVerificationSheet?.present(
                // Set the verification session ID.
                verificationSessionId = id,
                // Set the ephemeral key secret.
                ephemeralKeySecret = key
            )
        }
```
[StripeIdentityPlugin.kt#L107](https://github.com/jeremiahseun/Stripe-Identity/blob/3c8a677a81c7cf73d46ff6fc25d782928da89961/android/src/main/kotlin/com/stripe/identity/identity/StripeIdentityPlugin.kt#L107)

The above snippet happens in the methodChannel call and that's the reason you are faced with that error. Indeed it's an error with the library.
Should be an easy fix, move the sheet create call out of here and into an initialization function. Not sure where that is yet since the scope is a flutter plugin but will find time to look into this issue!

**Comment by jeremiahseun** [comment]
This too is fixed based on the last PR

**Comment by jeremiahseun** [comment]
@juleshyacinthe check for v1.0.3 and try the process again. If it remains, reopen this issue again.

**Comment by iambenkay** [comment]
I don't think the last PR will fix this.

This issue is peculiar to the way the native sheet is being initiated in the method channel call

**Comment by juleshyacinthe** [comment]
I can confirm that the issue is still happening with v1.0.3 of the package. I can't reopen the issue myself though.

**Comment by StephanWalters** [comment]
Is anyone working on this? If not I will try @iambenkay in few and raise a PR if it fixes the android issue.

**Comment by iambenkay** [comment]
Try it out and send in a PR 🔥

**Comment by StephanWalters** [comment]
@iambenkay @jeremiahseun created a PR with a fix. However, it only works on a real device not emulator.

https://github.com/jeremiahseun/Stripe-Identity/pull/6

**Comment by jeremiahseun** [comment]
@juleshyacinthe try `stripe_identity_plugin: ^1.0.4` and see if you are still facing the issue. If it happens to persist, please reopen this issue.

**Comment by juleshyacinthe** [comment]
Great news! The plugin isn't crashing anymore, however, you should add the Android setup in the readme file (https://github.com/jeremiahseun/Stripe-Identity/pull/6#issue-2939996997), I had to go get it in the pull request.

**Comment by StephanWalters** [comment]
@juleshyacinthe omg lol. it takes a community. You should fork the code and update the README since you just did it. Else, I will do it tomorrow if i dont see a PR up. We will probably need to increment the version as well.
